name: Deploy to Vercel (Production)

# env:
#   VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

on:
  workflow_dispatch:

jobs:
  Build-and-deploy:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # - name: Check vercel project settings # Use this to get the org id and project id
      #   run: cat ~/work/lloyds-nuxt-test/lloyds-nuxt-test/.vercel/project.json

      - name: Vercel Build Project Artifacts # https://youtu.be/FHVaWZjWec4?t=254
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel Production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
